version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: npm start
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    # volumes:
      # - ./frontend:/usr/share/nginx/html
    restart: unless-stopped
